/* Comments are generated by ChatGPT for future references */

// Import React library to create React components
import React, {useState, useEffect} from 'react';


// Import the Background component from a file with the alias '@/components/Background'
import Background from '@/components/Background';

import checkAuthMiddleware from '@/middleware/checkAuthMiddleware';


// Import the Login component from a file with the alias '@/components/Login'
import Login from '@/components/Login';
import { useRouter } from 'next/router';

import { auth, database } from '../Firebase/firebase'
import { get, set, ref } from 'firebase/database'

// Define a functional React component named Homepage
const Homepage: React.FC = () => {
    const [ authenticate, setAuthenticate] = useState<boolean>(true);
    const router = useRouter();

    useEffect(()=>{
        checkAuthMiddleware((uid)=>{
            if(uid){
                
                const userRef = ref(database, `users/${uid}`);
                get(userRef)
                .then((snapshot)=>{
                    if(snapshot.exists()){
                        router.replace('/dashboard')
                    }
                })
            }
            else{
                setAuthenticate(false);
            }
        });
    }, [router]);


    if(authenticate){
        return null;
    }
    else{
        return<>
            <Background />
            <Login />
        </>
    }
}

// Export the Homepage component as the default export of this module
export default Homepage;
